//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "id": "64208e0e636975414fa1161c"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Otto",
  "email": "otto@mail.com",
  "password": "test"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "mimmi@mail.com",
  "password": "test"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/:id 
Content-Type: application/json

{
  "_id":"643eedf02b9101b1feca3e4e"
}

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Produkt 2",
  "description": "Beskrivning av produkt 2",
  "price": 140, 
  "lager": 30
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "orderNumber": 6374,
  "products": ["64209124b85783fbde44e47a", "643eedf02b9101b1feca3e4e"],
  "quantity": 2,
  "user": "641dfd90af11920a280ca100"
  
}

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###